@localhost=localhost:4004/odata/v4/main
@id=ceb950eb-76fd-438b-a190-0f728fc8c0eb
@productID=1

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "ID": "ceb950eb-76fd-438b-a190-0f728fc8c0f0",
    "customer_ID": "ceb950eb-76fd-438b-a190-0f728fc8c0eb",
    "items": [
        {
            "product_ID": "ceb950eb-76fd-438b-a190-0f728fc8c0e1",
            "quantity": 10,
            "price": 10.98
        },
        {
            "product_ID": "ceb950eb-76fd-438b-a190-0f728fc8c0e2",
            "quantity": 2,
            "price": 20
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders({{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/SalesOrderHeaders({{id}})
Content-Type: application/json

{
    "name": "Pedido Alterado"
}